version: '3.8'
services:
  pg_database:
    image: postgres
    container_name: pg_database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_database:/var/lib/postgresql/data
  
volumes:
  pg_database: 